export const companyConfig = {
  name: process.env.NEXT_PUBLIC_COMPANY_NAME || "RheinAhr Dienstleistungen GmbH",
  shortName: process.env.NEXT_PUBLIC_COMPANY_SHORT_NAME || "RheinAhr",
  street: process.env.NEXT_PUBLIC_COMPANY_ADDRESS_STREET || "Theaterplatz 1",
  city: process.env.NEXT_PUBLIC_COMPANY_ADDRESS_CITY || "53177 Bonn",
  phone: process.env.NEXT_PUBLIC_COMPANY_PHONE || "+49 (0) 228 / 28683821",
  fax: process.env.NEXT_PUBLIC_COMPANY_FAX || "+49 (0) 228 / 36039105",
  mobile: process.env.NEXT_PUBLIC_COMPANY_MOBILE || "+49 (0) 152 / 33 64 65 62",
  email: process.env.NEXT_PUBLIC_COMPANY_EMAIL || "info@rheinahr-gmbh.de",
  website: process.env.NEXT_PUBLIC_COMPANY_WEBSITE || "www.rheinahr-gmbh.de",
  websiteUrl: process.env.NEXT_PUBLIC_COMPANY_WEBSITE_URL || "https://www.rheinahr-gmbh.de",
  registryCourt: process.env.NEXT_PUBLIC_COMPANY_REGISTRY_COURT || "Amtsgericht Bonn",
  hrb: process.env.NEXT_PUBLIC_COMPANY_HRB || "HRB 23459",
  taxId: process.env.NEXT_PUBLIC_COMPANY_TAX_ID || "206/5946/0589",
  vatId: process.env.NEXT_PUBLIC_COMPANY_VAT_ID || "DE316507908",
  ceo: process.env.NEXT_PUBLIC_COMPANY_CEO || "Basem Aldanaf",
  bankName: process.env.NEXT_PUBLIC_COMPANY_BANK_NAME || "Postbank",
  iban: process.env.NEXT_PUBLIC_COMPANY_IBAN || "DE62440100460387966464",
  bic: process.env.NEXT_PUBLIC_COMPANY_BIC || "PBNKDEFF",
  logoUrl: process.env.NEXT_PUBLIC_COMPANY_LOGO_URL || "/logo.png",
};
